<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Contact\Block\ContactForm $block */
?>

<p style="text-center" class="printArea"></p>

<div class="row">
	<div class="col-md-7">
	
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field telephone">
            <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment"><span><?= $block->escapeHtml(__('Message')) ?></span></label>
            <div class="control">
                <textarea style="font-size: 14px;" name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('Message')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
            </div>
        </div>
        <?php //$block->getChildHtml('form.additional.info') ?>
        
        <div>
            
<!-- Code start for google Recaptcha  -->
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$recaptcha = $objectManager->create('MSP\ReCaptcha\Model\Config');
 ?>
 
<style>
#g-recaptcha-response {
    display: block !important;
    position: absolute;
    margin: -78px 0 0 0 !important;
    width: 302px !important;
    height: 76px !important;
    z-index: -999999;
    opacity: 0;
}

.contact_faq {
    background: #eee;
    border-radius: 5px;
    padding: 20px;
    margin-bottom: 20px;
}

.contact_faq h2 {
    font-weight: bold;
    font-size: 20px;
}

.contact_faq p {
    font-size: 17px;
}

.faq_btn {
    text-align: center;
}

.faq_btn a {
    background: #9aca3c;
    font-size: 15px;
    padding: 6px 13px;
    text-align: center;
    color: #fff !important;
    text-decoration: none;
}

.vasl2 {
    font-size: 21px !important;
}

textarea.input-text{ width: 365px; max-width: 100%; }

.field label {
    display: inline-block !important;
    font-size: 13px;
    font-family: "Helvetica Neue", Verdana, Arial, sans-serif;
    font-weight: 600;
    -moz-user-select: none;
    -ms-user-select: none;
    -webkit-user-select: none;
    -o-user-select: none;
    user-select: none;
	width: 110px; 
	text-align: left;
}

.field .control{display: inline;}

</style>
	<div id="recaptcha_div"></div>
	<script>
      var onloadCallback = function() {
        grecaptcha.render('recaptcha_div', {
          'sitekey' : <?php echo "'".$recaptcha->getPublicKey()."'";?>
        });
      };
	  
	window.onload = function() {
		var recaptcha = document.querySelector('#g-recaptcha-response');

		if(recaptcha) {
			recaptcha.setAttribute("required", "required");
		}
	};
    </script>	
    <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit" async defer></script>  

<!-- Code end for google Recaptcha  -->
            
        </div>
        
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>


</div>
	
	<div class="col-md-5">
           
			<div class="contact_faq">
				<h2>OUR MAILING ADDRESS</h2>
				<p>955 Challenger Drive<br>Green Bay, WI 54311 </p>
			</div>

	</div>
	
</div>