<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php


$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
//$appState = $objectManager->get('\Magento\Framework\App\State');
//$appState->setAreaCode('frontend');
 
$categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
$categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
$categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository');
$categoryId = 129; // CATEGORY ID
$category = $categoryFactory->create()->load($categoryId);
$_productCollection = $category->getProductCollection()
                             ->addAttributeToSelect('*')
                             ->setOrder('position','ASC');;


$_helper = $this->helper('Magento\Catalog\Helper\Output');
$cartHelper = $objectManager->get('\Magento\Checkout\Helper\Cart'); 

$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');


?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();?>
    
	<div id="product_slider">
				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
		<?php $i=1; foreach ($_productCollection as $_product): ?>
				
		<div class="col-sm-6 col-md-4">
				<div class="media">
					
					<div class="media-left">
                        <?php 
						$productImage = $block->getImage($_product, $imageDisplayArea);
						if ($pos != null) {
							$position = ' style="left:' . $productImage->getWidth() . 'px;'
								. 'top:' . $productImage->getHeight() . 'px;"';
						}
						
						?>
						<?php // Product Image ?>
						<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
							<?  //echo $productImage->toHtml() ?>
							
							<?php
							   
							$productImage = $_imagehelper->init($_product, 'product_page_image_small')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(125)->getUrl();
							//$productImage = $_imagehelper->init($_product, 'product_page_image_small')->getUrl();
							?>

							<img class="lazyload" data-src="<?php echo $productImage; ?>" />
							
						</a>
                    </div>
	
					<div class="media-body">
							<p>Terry Naturally</p>
							<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
								<a class="name"
								   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
									<?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
								</a>
						
							<? /* @escapeNotVerified */ //$block->getProductPrice($_product) ?>
							<?= $block->getProductDetailsHtml($_product) ?>
							
							
							
							<div class="product-item-inner">
								<div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
									<div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
									<?php 
										$customOptions = $objectManager->get('Magento\Catalog\Model\Product\Option')->getProductOptionCollection($_product);
										$finalOption = array();
										$hasOptions = false;
										foreach($customOptions as $optionKey => $optionVal){
											$hasStock = false;
											$availabaleOptions = array();
											foreach($optionVal->getValues() as $valuesKey => $valuesVal){
												if($valuesVal->getInStock() == '0'){continue;};
												$availabaleOptions[] = $valuesVal;
												$hasStock = true;
											}
											if($hasStock){
												$finalOption[] = array(
													'id' => $optionVal->getId(),
													'value' => $availabaleOptions //$optionVal->getValues()
												);
												$hasOptions = true;
											}
										}
									?>
										
										
										<?php if ($_product->isSaleable() && $hasOptions): ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ /*$postParams['action']*/ $cartHelper->getAddUrl($_product) ?>" method="post">
												<input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
												<input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
												<input type="hidden" name="milople_subscription_type" value="-1" />
												<input type="hidden" name="milople_subscription_type_label" value="" />
												<?= $block->getBlockHtml('formkey') ?>
												<div>
													<?php
														$optStr = "";
														foreach($finalOption as $optionKey => $optionVal){
															$optStr .= "<div class='custom-options'>";
																$optStr .= "<select class='selectpicker' name='options[".$optionVal['id']."]'>";
																foreach($optionVal['value'] as $valuesKey => $valuesVal) {
																	$optStr .= "<option value='".$valuesVal->getId()."'>$".number_format($valuesVal->getPrice(),2).'&nbsp;&nbsp;&nbsp;'.$valuesVal->getTitle()."</option>";
																}
															$optStr .= "</select></div>";
														}
														echo($optStr);
													?>
												</div>
												<div class="btn-group addtocart" role="group" aria-label="...">
													  <button type="button" class="btn action primary btn_minus">-</button>
													  <input type="number"
																	   name="qty"
																	   value="1"
																	   title="<?= /* @escapeNotVerified */ __('Qty') ?>"
																	   class="input-text qty"
																	   data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
																	   />
													  <button type="button" class="btn action primary btn_plus">+</button>
													<button type="submit"
															title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
															class="action tocart primary">
														<span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
													</button>
												</div>
												
												<div>
													
												</div>
											</form>
										<?php else: ?>
											<?php if ($_product->isAvailable()): ?>
												<div class="stock available"><span><?= /* @escapeNotVerified */ __('Out of stock at this time') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock at this time') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
									<div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
										<?php if ($addToBlock = $block->getChildBlock('addto')): ?>
											<?= $addToBlock->setProduct($_product)->getChildHtml() ?>
										<?php endif; ?>
									</div>
								</div>
								
								
							</div>
							
							
						
							
						</div>
				
				</div>
				</div>
				<?php endforeach; ?>
			</div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>