<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>

<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
		<div class="btn-group addtocart" role="group" aria-label="...">
			  <button type="button" class="btn action primary btn_minus">-</button>
			  <input type="number"
                       name="qty"
                       id="qty"
                       value="1"
                       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
			  <button type="button" class="btn action primary btn_plus">+</button>
				<button type="submit"
						title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
						class="action primary tocart"
						id="product-addtocart-button">
					<span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
				</button>
			<?= $block->getChildHtml('', true) ?>
		</div>
		<?php endif; ?>
    </div>
</div>
<?php endif; ?>

