<div class="description">
	<?php
		$_product = $block->getProduct();
		echo __($_product->getDescription());
	?>
	<div>
	<?php echo __($_product->getProduct_awards()); ?>
	</div>
	<div>
	<?php echo __($_product->getAdditional_description()); ?>
	</div>
	<br>
	<?php
		if($_product->getVideoid()){
	?>
		<iframe width="420" height="315" style="max-width: 100%" src="<?php echo $_product->getVideoid(); ?>" frameborder="0" allowfullscreen=""></iframe>
	<?
		}
	?>
	
</div>
