<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Review\Block\Form $block */
?>

<style>
    .block-content div {
     background: #fff;
     padding: 0 !important;
     margin: initial !important;
     box-shadow: none;
     border-top: none; 
}

a.action.back:before {
    content: '<<';
    font-size: 8px;
    vertical-align: middle;
    margin-right: 5px;
}
.product-social-links {
    display: none;
}

.fieldset:last-child {
    margin-bottom: 0;
    border-bottom: 1px solid #ededed;
}

.label {
    text-transform: uppercase;
    font-size: 12px;
}

.label span {
    font-weight: normal;
    color: #636363 !important;
}

.action.submit.primary {
    background: #9BCA3C !important;
    border: none;
    border-radius: 0 !important;
    text-transform: uppercase;
}
.action.submit.primary:hover{
    background:#006224;
}

.action.submit.primary span{
    color:#fff;
}
li.item.review-item {
    padding: 0;
    margin-left: 0;
}
.reviewed_by *{
    color: #3399cc !important;
    
}
#customer-reviews .review-details-label, #customer-reviews .review-details-value{font-weight:normal;}
.review-add .block-title {
    display: block;
    border:none;
}
div#customer-reviews {
    margin: 0;
}
.r_title,.r_rev {
    font-size: 12px;
    text-transform: uppercase;
    margin-bottom: 0;
}
.r_title,.r_rev span{color: #39c !important;}
.review-title {
    color: #006224 !important;
    text-transform: uppercase;
    font-size: 14px;
}

</style>


<div class="block review-add">
    <p class="r_title">Write Your Own Review</p>
<div class="block-content">
<?php if ($block->getAllowWriteReviewFlag()): ?>
<form action="<?= $block->escapeUrl($block->getAction()) ?>" class="review-form" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'">
    <?= $block->getBlockHtml('formkey') ?>
    <?= $block->getChildHtml('form_fields_before') ?>
    <fieldset class="fieldset review-fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">

         <p class="r_rev">You're reviewing:<span><?= $block->escapeHtml($block->getProductInfo()->getName()) ?></span></p><br>
        
        <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
        <span id="input-message-box"></span>
        <fieldset class="field required review-field-ratings">
            <legend class="label"><span><?= $block->escapeHtml(__('Your Rating')) ?></span></legend><br/>
            <div class="control">
                <div class="nested" id="product-review-table">
                    <?php foreach ($block->getRatings() as $_rating): ?>
                        <div class="field choice review-field-rating">
                            <label class="label" id="<?= $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label"><span><?= $block->escapeHtml($_rating->getRatingCode()) ?></span></label>
                            <div class="control review-control-vote">
                            <?php $options = $_rating->getOptions();?>
                            <?php $iterator = 1; foreach ($options as $_option): ?>
                                <input
                                    type="radio"
                                    name="ratings[<?= $block->escapeHtmlAttr($_rating->getId()) ?>]"
                                    id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>"
                                    value="<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                                    class="radio"
                                    data-validate="{'rating-required':true}"
                                    aria-labelledby="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_rating_label <?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label" />
                                <label
                                    class="rating-<?= $block->escapeHtmlAttr($iterator) ?>"
                                    for="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>"
                                    title="<?= $block->escapeHtmlAttr(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?>"
                                    id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label">
                                    <span><?= $block->escapeHtml(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?></span>
                                </label>
                            <?php $iterator++; ?>
                            <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
            </div>
        </fieldset>
    <?php endif ?>


        <div class="field review-field-text required">
            <label for="review_field" class="label"><span><?= $block->escapeHtml(__('Let us know your thoughts')) ?></span></label>
            <div class="control">
                <textarea name="detail" id="review_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
            </div>
        </div>
        
        		
        <div class="field review-field-summary required">
            <label for="summary_field" class="label"><span><?= $block->escapeHtml(__('Summary of Your Review')) ?></span></label>
            <div class="control">
                <input type="text" name="title" id="summary_field" class="input-text" data-validate="{required:true}" data-bind="value: review().title" />
            </div>
        </div>
        
       <div class="field review-field-nickname required">
            <label for="nickname_field" class="label"><span><?= $block->escapeHtml(__("What's your nickname?")) ?></span></label>
            <div class="control">
                <input type="text" name="nickname" id="nickname_field" class="input-text" data-validate="{required:true}" data-bind="value: nickname()" />
            </div>
        </div>
        
	   <div class="field review-field-nickname required">
            <label for="email_field" class="label"><span><?= $block->escapeHtml(__('Your Email')) ?></span></label>
            <div class="control">
               		<input type="text" name="email" id="email_field" class="input-text validate-email" data-validate="{required:true}"/>
            </div>
        </div>
        
        
        
        <div>
                <input type="checkbox" name="disclaimer" checked="checked" class="required-entry" aria-label="disclaimer" required="required">
                I give and grant to Terry Naturally Vitamins the right to use, publish, my name, and testimonial in all media and types of advertising and promotion.<br>
                <br>
                I agree that no advertisement or other material needs to be submitted to me for any further approval. I grant Terry Naturally Vitamins unrestricted, unlimited right and permission to use, reproduce, copyright, publish, publish to the Internet, and exhibit in any form and manner whatsoever, the testimonial that I now submit electronically.  I further agree that Terry Naturally Vitamins will have the right to attribute the above statement (or statements in different words which have substantially the same meaning) to me, which is an expression of my personal expression and belief.
        </div>
        <br>
		
<!-- Code start for google Recaptcha  -->
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$recaptcha = $objectManager->create('MSP\ReCaptcha\Model\Config');
 ?>
 
<style>
#g-recaptcha-response {
    display: block !important;
    position: absolute;
    margin: -78px 0 0 0 !important;
    width: 302px !important;
    height: 76px !important;
    z-index: -999999;
    opacity: 0;
}
</style>
	<div id="recaptcha_div"></div>
	<script>
      var onloadCallback = function() {
        grecaptcha.render('recaptcha_div', {
          'sitekey' : <?php echo "'".$recaptcha->getPublicKey()."'";?>
        });
      };
	  
	window.onload = function() {
		var recaptcha = document.querySelector('#g-recaptcha-response');

		if(recaptcha) {
			recaptcha.setAttribute("required", "required");
		}
	};
    </script>	
    <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit" async defer></script>  

<!-- Code end for google Recaptcha  -->

   
    </fieldset>
    <div class="actions-toolbar review-form-actions">
        <div class="primary actions-primary">
            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Submit Review')) ?></span></button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
{
    "[data-role=product-review-form]": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    },
    "#review-form": {
        "Magento_Review/js/error-placement": {},
        "Magento_Review/js/validate-review": {}
    }
}
</script>
<?php else: ?>
    <div class="message info notlogged" id="review-form">
        <div>
            <?= $block->escapeHtml(__('Only registered users can write reviews. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()), ['a']) ?>
        </div>
    </div>
<?php endif ?>
</div>
</div>

<script type="text/javascript">
        require(['jquery'], function($) {
            jQuery(document).ready(function(){
                jQuery(".product-reviews-summary").prependTo(".extra-info");
            });
        });
</script>
